### ISSUE TITLE
5 titres dont la structure XML-TEI est validée à passer en word pour relecture, merci!

### ISSUE THREAD

**Issue by etymologika** [galenus-verbatim/galenus_scriptorium#1]
https://galenus-verbatim.github.io/galenus_cts/data/tlg0057/tlg111/tlg0057.tlg111.verbatim-grc1.xml
https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg002/tlg0530.tlg002.verbatim-grc1.xml
https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg023/tlg0530.tlg023.verbatim-grc1.xml
https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg035/tlg0530.tlg035.verbatim-grc1.xml
https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg037/tlg0530.tlg037.verbatim-grc1.xml

**Comment by glorieux-f** [comment]
Je crois que c’est bon, Word ne pleure pas quand on ouvre le document (et ce n’est pas toujours le même titre)

**Comment by etymologika** [comment]
c'est parfait, merci!
