### ISSUE TITLE
7 titres dont la structure XML-TEI est validée à passer en word pour relecture, merci!

### ISSUE THREAD

**Issue by etymologika** [galenus-verbatim/galenus_scriptorium#2]
https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg042/tlg0530.tlg042.verbatim-grc1.xml
https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg024/tlg0530.tlg024.verbatim-grc1.xml
https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg033/tlg0530.tlg033.verbatim-grc1.xml
https://galenus-verbatim.github.io/galenus_cts/data/tlg0057/tlg106/tlg0057.tlg106.verbatim-grc1.xml
https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg022/tlg0530.tlg022.verbatim-grc1.xml
https://galenus-verbatim.github.io/galenus_cts/data/tlg0057/tlg037/tlg0057.tlg037.verbatim-grc1.xml
https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg036/tlg0530.tlg036.verbatim-grc1.xml

**Comment by glorieux-f** [comment]
Dans https://github.com/galenus-verbatim/galenus_scriptorium/tree/main/0_brut

**Comment by etymologika** [comment]
merci! tvb sauf pour https://github.com/galenus-verbatim/galenus_scriptorium/blob/main/0_brut/tlg0530.tlg022.verbatim-grc1.docx qui refuse de s'ouvrir, aussi bien dans Word que dans LibreOffice
