### ISSUE TITLE
Teinte pour 20 fichiers word, merci!

### ISSUE THREAD

**Issue by etymologika** [galenus-verbatim/galenus_scriptorium#23]
Merci de passer en xml les fichiers du dossier https://github.com/galenus-verbatim/galenus_scriptorium/tree/main/9bis_a_passer_en_xml
Voici les styles utilisés:
 &lt;pb&gt;:  &lt;pb n="19.XXX"/&gt;
 &lt;lb&gt;:  &lt;lb n="XXX"/&gt;
 &lt;num&gt;:
pour work,  &lt;div type="textpart" subtype="work" n="1" xml:id="_1"&gt;
pour chapter,  &lt;div type="textpart" subtype="chapter" n="XXX" xml:id="_XXX"&gt;
 &lt;milestone&gt;:
pour ed1,  &lt;milestone unit="ed1page" n="X.XXX"/&gt;
pour ed2,  &lt;milestone unit="ed2page" n="XX.XXX"/&gt;
 &lt;label&gt;:  &lt;label type="head"&gt;
 &lt;p&gt;: &lt;p rend="indent"&gt;
 &lt;l&gt;:  &lt;l&gt;
Laisser les tableaux tels quels, ils seront formatés dans un 2e temps.
Les fichiers xml produits sont destinés à remplacer les fichiers de même nom présents ici: https://github.com/galenus-verbatim/galenus_cts/tree/master/data

**Comment by glorieux-f** [comment]
Je pense avoir fait au mieux.

**Comment by etymologika** [comment]
merci beaucoup!
